
LIB_NAME=AnimationGradients
CFLAGS=-DDEBUG -fblocks
LDLIBS= -llog -landroid -lCoreFoundation -lFoundation -lNAOpenGLES -lNACoreGraphics -lNAUIKit
OBJECTS = \
    rd_app_glue.o \
    rd_main.o \
    AppDelegate.o \
    AnimationGradientsView.o \

include ${MYOS_PATH}/android/sdk/resources/makefile-shared
